// plugins/withDevCaTrust.js — trust the local dev CA in Android debug builds.
//
// WHY THIS EXISTS
//
// The stack terminates TLS with a self-signed cert (docker/certs/localhost.crt)
// whose SANs now include the host's LAN IP so a physical phone can reach
// https://<LAN-IP>:18443. Issuing that cert is only half the job: since
// Android 7.0 (API 24) an app does NOT trust user-installed CAs by default.
// A phone with the dev CA installed will still fail the handshake with
// "ERR_CERT_AUTHORITY_INVALID" unless the app declares a trust configuration
// that opts into the user store. The generated debug manifest only sets
// usesCleartextTraffic="true", which is about plaintext, not trust anchors.
//
// Writing android/app/src/main/res/xml/network_security_config.xml by hand
// is not an option: `android/` is gitignored (mobile/.gitignore:41) and is
// destroyed by every `expo prebuild --clean`. A config plugin is evaluated at
// prebuild time, so the file is regenerated on every clean build.
//
// SECURITY: THIS MUST NEVER APPLY TO A SHIPPED BUILD.
//
// Trusting the user CA store means trusting *every* CA the user has ever
// installed — corporate MDM roots, debugging proxies, and any other app's
// injected root. That is an interception risk, not a convenience. So the
// trust anchor is injected into src/debug/ ONLY, never src/main. A debug
// variant cannot reach the Play Store, and the release variant has no
// network security config at all, so production keeps Android's default
// system-CA-only policy.
//
// The plugin also refuses to run unless the release channel is explicitly
// "development", so a misconfigured env cannot silently widen the trust
// boundary in a preview build.

const fs = require('fs');
const path = require('path');
const { XML, withDangerousMod } = require('expo/config-plugins');

const NETWORK_SECURITY_CONFIG = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by plugins/withDevCaTrust.js — do not edit by hand.

  Debug-only trust configuration. The user store holds the self-signed dev CA
  (docker/certs/localhost.crt). It is required because Android 7+ ignores
  user-installed CAs by default, and it lives in src/debug/ so the release
  variant never inherits it.
-->
<network-security-config>
    <!-- Metro serves the JavaScript bundle over HTTP. This file is emitted
         only into Android's debug source set, so it cannot affect a shipped
         preview or production build. -->
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
            <certificates src="user" />
        </trust-anchors>
    </base-config>
</network-security-config>
`;

const DEV_CA_TRUST = { allow: true };

module.exports = function withDevCaTrust(config, props = {}) {
  const { releaseChannel } = props;

  // Fail closed. An unset channel must not be read as "development" — that
  // would turn a missing env var into a weakened TLS trust boundary.
  if (releaseChannel !== 'development') {
    if (releaseChannel === undefined) {
      throw new Error(
        'withDevCaTrust requires an explicit releaseChannel. Refusing to guess, ' +
          'because defaulting to "development" would inject a user-CA trust ' +
          'anchor into a build that may ship.',
      );
    }
    return config;
  }

  config = withDangerousMod(config, [
    'android',
    async (cfg) => {
      const androidRoot = cfg.modRequest.platformProjectRoot;

      // src/debug/ — NOT src/main/. See the SECURITY note above.
      const debugRes = path.join(androidRoot, 'app', 'src', 'debug', 'res');
      const xmlDir = path.join(debugRes, 'xml');
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, 'network_security_config.xml'), NETWORK_SECURITY_CONFIG);

      // Patch src/debug/AndroidManifest.xml, not the main manifest.
      //
      // withAndroidManifest would edit src/main/AndroidManifest.xml, which is
      // the WRONG file: it would put `android:networkSecurityConfig` on the
      // release variant too, where the resource above does not exist — the
      // release build would then fail to resolve @xml/network_security_config
      // (or, worse, resolve against a stale merged resource). Editing the
      // debug manifest keeps the attribute and the resource in the same
      // source set, which is the only pairing that is safe.
      const debugManifest = path.join(androidRoot, 'app', 'src', 'debug', 'AndroidManifest.xml');

      // XML.readXMLAsync / writeXMLAsync come from expo/config-plugins itself.
      // Requiring `xml2js` directly does NOT work here: config-plugins bundles a
      // jsdom-backed fork whose parser is not exported as `xml2js`, so the
      // standalone package resolves to an incompatible object and the mod dies
      // with "xml2js is not a function". These helpers are the supported
      // round-trip and also handle Android's attribute escaping.
      //
      // Both take `{ path }`, NOT a bare string. Given a string, readXMLAsync
      // swallows the read error, falls back to parsing an empty string, and
      // returns null — so the failure surfaces as "Cannot read properties of
      // null (reading 'manifest')" with no mention of the path. That null is
      // indistinguishable from a genuinely empty file, hence the guard below.
      const manifest = await XML.readXMLAsync({ path: debugManifest });
      if (!manifest) {
        throw new Error(`withDevCaTrust: could not parse ${debugManifest}`);
      }

      const application = manifest.manifest?.application?.[0];
      if (!application) {
        throw new Error(`withDevCaTrust: no <application> in ${debugManifest}`);
      }
      application.$ = application.$ || {};
      application.$['android:networkSecurityConfig'] = '@xml/network_security_config';

      await XML.writeXMLAsync({ path: debugManifest, xml: manifest });
      return cfg;
    },
  ]);

  return config;
};
