#!/usr/bin/env bash
#
# run-hls-worker-local.sh — start the HLS token Worker against local MinIO.
#
# WHY THIS SCRIPT EXISTS
#
# The Worker and Django share one secret (MEDIA_TOKEN_SECRET). If they drift,
# every playback token is rejected and you get a wall of 403s that looks
# exactly like an expired token or a clock-skew bug. Nothing in either
# codebase can detect the mismatch, so this script removes the possibility:
# it renders .dev.vars from the repo's .env.local every time, then execs
# wrangler dev. Run this (or `npm run dev` in workers/hls-token-worker)
# rather than bare `wrangler dev`.
#
# The Worker additionally fails loudly at /healthz when MEDIA_TOKEN_SECRET is
# unset. It cannot detect a *mismatched* secret — only a shared source can.
#
# USAGE
#   scripts/run-hls-worker-local.sh              # start on 0.0.0.0:8787
#   scripts/run-hls-worker-local.sh --port 9000  # override the port
#
# NOTE: wrangler does NOT hot-reload .dev.vars -- it watches source files, not
# var files -- so editing .dev.vars by hand has no effect until the process is
# restarted. Re-running this script both regenerates the file and restarts the
# Worker, which is the point of routing `npm run dev` through it.
#
# WHY 0.0.0.0 AND NOT 127.0.0.1
#
# The nginx container reaches the Worker over the Docker bridge, which cannot
# see the host's loopback interface. It resolves the host via the
# `host.docker.internal:host-gateway` extra_hosts entry in
# docker-compose.local.yml, so the Worker must be bound to a routable
# address. See docker/nginx.local.conf for the upstream that points at it.
#
# CONSEQUENCE: the Worker is reachable from anything that can route to this
#machine's LAN address while it runs. It holds no HLS data of its own (it
#proxies to MinIO after validating a token) and it refuses unauthenticated
#requests, so the exposure is a validating proxy, not a media server. Do not
#leave it running on a shared or untrusted network.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
WORKER_DIR="${REPO_ROOT}/workers/hls-token-worker"
ENV_LOCAL="${REPO_ROOT}/.env.local"
DEV_VARS="${WORKER_DIR}/.dev.vars"

HOST="${HLS_WORKER_HOST:-0.0.0.0}"
PORT="${HLS_WORKER_PORT:-8787}"

if [[ ! -f "${ENV_LOCAL}" ]]; then
    echo "error: ${ENV_LOCAL} not found." >&2
    echo "       cp .env.example .env.local and fill it in first." >&2
    exit 1
fi

# Read one KEY=VALUE out of .env.local. Deliberately not `source`: that file
# contains values with spaces and base64 characters that would be mangled by
# the shell, and sourcing arbitrary env files is a footgun.
read_env() {
    local key="$1"
    sed -n "s/^${key}=//p" "${ENV_LOCAL}" | head -1
}

require() {
    local key="$1" value="$2"
    if [[ -z "${value}" ]]; then
        echo "error: ${key} is missing or empty in ${ENV_LOCAL}" >&2
        exit 1
    fi
}

MEDIA_TOKEN_SECRET="$(read_env MEDIA_TOKEN_SECRET)"
AWS_ACCESS_KEY_ID="$(read_env AWS_ACCESS_KEY_ID)"
AWS_SECRET_ACCESS_KEY="$(read_env AWS_SECRET_ACCESS_KEY)"
AWS_STORAGE_BUCKET_NAME="$(read_env AWS_STORAGE_BUCKET_NAME)"
AWS_S3_REGION_NAME="$(read_env AWS_S3_REGION_NAME)"
MEDIA_TOKEN_TTL_SECONDS="$(read_env MEDIA_TOKEN_TTL_SECONDS)"

require MEDIA_TOKEN_SECRET "${MEDIA_TOKEN_SECRET}"
require AWS_ACCESS_KEY_ID "${AWS_ACCESS_KEY_ID}"
require AWS_SECRET_ACCESS_KEY "${AWS_SECRET_ACCESS_KEY}"

AWS_STORAGE_BUCKET_NAME="${AWS_STORAGE_BUCKET_NAME:-echoflow-media}"
AWS_S3_REGION_NAME="${AWS_S3_REGION_NAME:-auto}"
MEDIA_TOKEN_TTL_SECONDS="${MEDIA_TOKEN_TTL_SECONDS:-600}"

# The host-published MinIO port, not the in-network address. `wrangler dev`
# runs in the host network namespace, so `minio-local:9000` (a Docker DNS
# name) does not resolve for it. docker-compose.local.yml publishes MinIO on
# 127.0.0.1:19000 for exactly this reason.
MEDIA_S3_ENDPOINT="${HLS_WORKER_MINIO_ENDPOINT:-http://127.0.0.1:19000}"

umask 077
cat > "${DEV_VARS}" <<EOF
# GENERATED by scripts/run-hls-worker-local.sh from .env.local — do not edit.
# Regenerate by re-running the script. Real secrets: this file is gitignored.
MEDIA_TOKEN_SECRET=${MEDIA_TOKEN_SECRET}
MEDIA_TOKEN_TTL_SECONDS=${MEDIA_TOKEN_TTL_SECONDS}
MEDIA_S3_ENDPOINT=${MEDIA_S3_ENDPOINT}
MEDIA_S3_BUCKET=${AWS_STORAGE_BUCKET_NAME}
MEDIA_S3_REGION=${AWS_S3_REGION_NAME}
MEDIA_S3_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
MEDIA_S3_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
EOF
chmod 600 "${DEV_VARS}"

echo "wrote ${DEV_VARS} (mode 600) from ${ENV_LOCAL}"
echo "  MEDIA_TOKEN_SECRET  <- shared with Django; must match"
echo "  MEDIA_S3_ENDPOINT    ${MEDIA_S3_ENDPOINT}"

if ! curl -sf -o /dev/null -m 3 "${MEDIA_S3_ENDPOINT}/minio/health/live" 2>/dev/null; then
    echo
    echo "warning: ${MEDIA_S3_ENDPOINT} is not answering /minio/health/live." >&2
    echo "         Is the stack up?  docker compose -f docker-compose.local.yml \\" >&2
    echo "           --env-file .env.local up -d" >&2
    echo "         The Worker will start, but every authorized request will 502." >&2
fi

if [[ "${1:-}" == "--port" ]]; then
    PORT="$2"
elif [[ -n "${1:-}" ]]; then
    echo "usage: $0 [--port N]" >&2
    exit 2
fi

cd "${WORKER_DIR}"
echo
echo "wrangler dev --ip ${HOST} --port ${PORT}"
exec npx wrangler dev --ip "${HOST}" --port "${PORT}"
