# Generated by Django 5.2.17 on 2026-09-28 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_20260913_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='clip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='app.audioclip'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_reason',
            field=models.CharField(choices=[('obscene', 'Obscene or sexually explicit'), ('hate_speech', 'Hate speech'), ('violence', 'Promotes violence'), ('csam', 'Child sexual abuse material'), ('terrorism', 'Terrorism or extremism'), ('copyright', 'Copyright infringement'), ('impersonation', 'Impersonation'), ('privacy', 'Invasion of privacy'), ('spam', 'Spam or misleading'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['clip', '-created_at'], name='app_report_clip_id_c4730e_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('clip__isnull', False)), fields=('user', 'clip'), name='unique_report_per_user_per_clip'),
        ),
    ]
