# Generated by Django 5.2.17 on 2026-09-28 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_report_clip_report_report_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentaudit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datasubjectrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_subject_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
